### ISSUE TITLE
format Date text using column header template

### ISSUE THREAD

**Issue by cmahaj** [eisenbraun/columns#14]
Is there a way we can format date text being recieved in JSON call (for eg. 2015-06-02T01:18:05.858Z) to be displayed as (02-Jun-2015 06:05 PM) using header template.

Additionally, if above is possible can we have sort on this date column sorts the result as per date and not as text.

**Comment by petejordan** [comment]
ditto

**Comment by vordan** [comment]
You can format your dates in the JSON object or even earlier, in SQL.
That's what I did..
