### ISSUE TITLE
Hide Column of Data

### ISSUE THREAD

**Issue by donlaur** [eisenbraun/columns#16]
Is there a way to hide a column of data?  Lets say you want to have a code for a product in the data but you do not want it displayed?  It is in your schema and JSON but not displayed on the columns?

**Comment by eisenbraun** [comment]
Yes, there is. If you add "hide": true on the column object inside your schema it will be available use, but will not display. 

I apologize that this was not documented.

**Comment by donlaur** [comment]
I added the "hide":true and it did not hide the column on the display.

**Comment by eisenbraun** [comment]
Can you send me a sample of your code?

**Comment by donlaur** [comment]
<script>
//example 3
$.ajax({
url:'jsonoutput.php?type=amentity',
dataType: 'json',
success: function(json) {
example3 = $('#example3').columns({
data:json,
showRows: [10, 20, 30, 40, 50],
size: 10,
query: '',
schema: [
{"header":"Map It", "key":"number", "template":'<a href="{{building}}_{{floor}}F.php"><img src="img/find-icon.png"></a>'},
{"header":"Amenity Name", "key":"name"},
{"header":"Building Code", "key":"building", "hide": true},
{"header":"Building Name", "key":"buildingname"},
{"header":"Floor", "key":"floor"},
{"header":"Room", "key":"number"}
]
});
}
});
</script>

**Comment by donlaur** [comment]
How do I contact you to send an email?

**Comment by eisenbraun** [comment]
You can contact me at krepta00@gmail.com.

**Comment by donlaur** [comment]
Updating the Columns plugin fixed this issue.  I had thought I had the newest version, but I guess not.  Thanks.

**Comment by timdmaxey** [comment]
Hi there, thank you btw for the columns! I wanted to know is there a way to invoke the sort outside of the headers? Like have the table in to page and a menu to the left for sorting? You could like "First Name" on the header (which works fine) then ALSO click a button to sort by First Name too..?

**Comment by donlaur** [comment]
I am not the developer, so they might have other ideas, but sure.

You can use the button to call a function, or send in a variable via a GET
in the URL.  If you use something like PHP you can get the variable of
sortby and then change in the columns setup.
I have created buttons to do that.  The buttons call a filter function.  It
is filter, but not sort, but pretty much similar.

**Comment by timdmaxey** [comment]
Hey thanks for the reply... so you calling filter function the columns table uses? Or you made your own filter function? I just want to want to call something to sort a column... Like it does now when you click on it...

**Comment by eisenbraun** [comment]
Please see my response on issue #17

**Comment by timdmaxey** [comment]
Thank you!
