### ISSUE TITLE
external URL/API

### ISSUE THREAD

**Issue by Frontend-Head** [eisenbraun/columns#29]
Hello,

is it possible to address an external URL or API? I'm afraid I can't find a way.

z. B: https://api.hotslogs.com/Public/Players/1/Benthor_1644

I'm hoping for an answer.
Thank you

**Comment by eisenbraun** [comment]
This version of Columns only works with arrays of objects and does not retrieve data from external source.  It maybe possible to use an external URL, but it would need to be retrieved $.ajax before calling the columns plugin.

Furthermore this version of Columns is no longer maintained.
